export const SELECTORS = {
  reviewsTab: 'button[aria-label*="Reviews"]',
  reviewsPanel: 'div.m6QErb.DxyBCb.kA9KIf.dS8AEf',
  reviewsPanelFallback: '[role="main"] [tabindex="-1"]',
  review: 'div[data-review-id]',
  authorName: '.d4r55',
  authorNameFallback: '[class*="d4r55"]',
  rating: 'span.kvMYJc',
  ratingFallback: '[role="img"][aria-label*="star"]',
  reviewText: '.wiI7pd',
  reviewTextFallback: '[class*="wiI7pd"]',
  expandButton: 'button.w8nwRe.kyuRq',
  expandButtonFallback: 'button[aria-expanded="false"][aria-label="See more"]',
  reviewDate: '.rsqaWe',
  reviewDateFallback: '[class*="rsqaWe"]',
  ownerResponse: '.CDe7pd',
  ownerResponseFallback: '[class*="CDe7pd"]',
  totalReviewCount: 'div.fontBodySmall[role="img"]',
  sortButton: 'button[aria-label="Sort reviews"]',
  sortNewest: 'div[data-index="1"]',
} as const;
